---
title: "CCE/PACT_Stability_project"
output:
  html_document: default
  pdf_document: default
date: "2025-05-02"
Aim: Visualize the figures showed in the stability project
Contact: lipei.shao@nih.gov
---

# Load required packages
```{r load required packages}
library(tidyverse)
library(dplyr)
library(colorspace)
library(readxl)
library(scales)
library(ggdendro)
library(ComplexHeatmap)
library(circlize)
library(dplyr)
library(ggplot2)
library(clusterProfiler)
library(org.Hs.eg.db)
library(enrichplot)
library(DOSE)
library(ReactomePA)
```

# Set parameters
```{r set parameters}
HPC_base <- "#1f77b4"  # blue
MNC_base <- "#d62728"  # red
HPC_day_color <- c("#0D1F2D", "#144A74", "#2878B5","#75AADB","#8799B0")
MNC_day_color <- c("#69000C","#CC1C2F","#FF999E","#b7796f","#A79393")
heatmap_colors <- colorRampPalette(c("darkgreen", "white", "purple4"))(100)
HPC_colors_day0day1 <- c("#0D1F2D", "#144A74")
pathway_color <- "orange3"
input_dir = "../02.Input/"
output_dir = "../03.Output/"
```

# Load data
```{r load data}
WBC <- read_excel(paste0(input_dir,'AllData.xlsx'),"WBC")
Viability <- read_excel(paste0(input_dir,'AllData.xlsx'),"Viability")
Donor_Viability <- read_excel(paste0(input_dir,'AllData.xlsx'),"Donor_Viability")
Lymphocytes <- read_excel(paste0(input_dir,'AllData.xlsx'),"Lymphocytes")
Neutrophils <- read_excel(paste0(input_dir,'AllData.xlsx'),"Neutrophils")
Monocytes <- read_excel(paste0(input_dir,'AllData.xlsx'),"Monocytes")
CD34 <- read_excel(paste0(input_dir,'AllData.xlsx'),"CD34")
TBNK <- read_excel(paste0(input_dir,'AllData.xlsx'),"TBNK")
NLRMLR <- read_excel(paste0(input_dir,'AllData.xlsx'),"NLRMLR")
hpc_PCA <- read_excel(paste0(input_dir,'AllData.xlsx'),"HPC_PCA")
mnc_PCA <- read_excel(paste0(input_dir,'AllData.xlsx'),"MNC_PCA")
hpc_ExpressionTPM <- read_excel(paste0(input_dir,'AllData.xlsx'),"HPC_ExpressionTPM")
mnc_ExpressionTPM <- read_excel(paste0(input_dir,'AllData.xlsx'),"MNC_ExpressionTPM")
```

# Figure1. WBC (1a) and Viability (1b)
```{r plot figure.1a and 1b}
##plot 1a
#statistical calculation (68% CI = mean ± 1*SE)
summary_df_WBC <- WBC %>%
  group_by(Day, Group,Type) %>%
  summarise(
    mean_val = mean(Value, na.rm = TRUE),      
    sd_val = sd(Value, na.rm = TRUE),
    n = sum(!is.na(Value)),
    se_val = sd_val / sqrt(n),
    ci_low = mean_val - se_val,   
    ci_high = mean_val + se_val
  )
#plot
WBC_plot <- ggplot(summary_df_WBC, aes(x = Day, y = mean_val, group = Group, color = Group, fill = Group)) +
  geom_line(size = 0.5) +
  geom_point(size = 1.2) +
  geom_ribbon(aes(ymin = ci_low, ymax = ci_high), alpha = 0.1, color = NA) +
    scale_color_manual(values = c("HPC" = HPC_base, "MNC" = MNC_base)) +
  scale_fill_manual(values = c("HPC" = HPC_base, "MNC" = MNC_base)) +
  labs( x = "Day relative to collection",
       y = "WBC/mL (10^6)") +
  theme_bw()+
  facet_grid(Group~Type)
#save plot
ggsave(paste0(output_dir,paste0("1a.WBC_across_timepoints.pdf")),width = 1.2*3, height = 1.0*2.5)

##plot 1b
#statistical calculation (68% CI = mean ± 1*SE)
summary_df_Viability <- Viability %>%
  group_by(Day, Group,Type) %>%
  summarise(
    mean_val = mean(Value, na.rm = TRUE),      
    sd_val = sd(Value, na.rm = TRUE),
    n = sum(!is.na(Value)),
    se_val = sd_val / sqrt(n),
    ci_low = mean_val - se_val,   
    ci_high = mean_val + se_val
  )
#plot
Viability_plot <- ggplot(summary_df_Viability, aes(x = Day, y = mean_val, group = Group, color = Group, fill = Group)) +
  geom_line(size = 0.5) +
  geom_point(size = 1.2) +
  geom_ribbon(aes(ymin = ci_low, ymax = ci_high), alpha = 0.1, color = NA) +
  scale_color_manual(values = c("HPC" = HPC_base, "MNC" = MNC_base)) +
  scale_fill_manual(values = c("HPC" = HPC_base, "MNC" = MNC_base)) +
  labs(x = "Day relative to collection",
       y = "Viability (% to 7-ADD)") +
  ylim(70,100)+
  theme_bw()+
  facet_grid(Group~Type)
#save
ggsave(paste0(output_dir,paste0("1b.Viability_across_timepoints.pdf")),width = 1.2*3, height = 1.0*2.5)
```

# Individual sample variability was notable
```{r plot figure to present the sample variability, label HPC group: donor1, donor6}
label_data <- Donor_Viability %>%
  filter(Group == "HPC", Donor %in% c("Donor1", "Donor6")) %>%
  group_by(Donor) %>%
  filter(Day == max(Day))
donor_via <- ggplot(Donor_Viability, aes(x = Day, y = Value, group = Donor)) +
  geom_line(color = "grey60", size = 0.2,linetype = "twodash") +
  geom_point(aes(color = factor(Day_Group)), size = 1.2) +
  geom_text(data = label_data, aes(label = Donor), 
            hjust = 0.8, vjust = 1.3, size = 2.5, show.legend = FALSE,fontface = "bold") +
  scale_color_manual(
    values = c("HPC0" = "#00366C", "HPC1" = "#468FD0", "HPC2" = "#A1C4F1", 
               "HPC3" = "#E1EEFF", "HPC4" = "#8799B0",
               "MNC0" = "#69000C", "MNC1" = "#CC1C2F", "MNC2" = "#FF999E", 
               "MNC3" = "#FFDEE0", "MNC4" = "#A79393"),
    breaks = NULL
  ) +
  labs(x = "Day relative to collection",
       y = "Viability (% to 7-ADD)") +
  ylim(70, 100) +
  labs(title = "Viability")+
  theme_bw() +
  facet_grid(Group ~ .)+
  theme(
    strip.background = element_blank(), 
    strip.text = element_text(face = "bold"),
    plot.title = element_text(hjust = 0.5, size = 11,face = "bold")  # Centered, larger, bold title
  )
ggsave(paste0(output_dir,paste0("S1d.Donor_Viability_inGroup.pdf")),width = 1.2*3, height = 1.2*2.5)
```

# Figure2. TBNK (2a), Neutrophils (2b), and Monocytes (2c)
```{r plot figure.2a, 2b and 2c}
##plot 2a
#statistical calculation (68% CI = mean ± 1*SE)
summary_df_Lymphocytes <- Lymphocytes %>%
  group_by(Day, Group,Type) %>%
  summarise(
    mean_val = mean(Value, na.rm = TRUE),      
    sd_val = sd(Value, na.rm = TRUE),
    n = sum(!is.na(Value)),
    se_val = sd_val / sqrt(n),
    ci_low = mean_val - se_val,   
    ci_high = mean_val + se_val
  )
#plot
Lymphocytes_plot <- ggplot(summary_df_Lymphocytes, aes(x = Day, y = mean_val, group = Group, 
                                                       color = Group, fill = Group)) +
  geom_line(size = 0.5) +
  geom_point(size = 1.2) +
  geom_ribbon(aes(ymin = ci_low, ymax = ci_high), alpha = 0.1, color = NA) +
    scale_color_manual(values = c("HPC" = HPC_base, "MNC" = MNC_base)) +
  scale_fill_manual(values = c("HPC" = HPC_base, "MNC" = MNC_base)) +
  labs(x = "Day relative to collection",
       y = "TBNK \n(% CD3/19/56+ to CD45+ cells)") +
  theme_bw()+
  facet_grid(Group~Type)
#save plot
ggsave(paste0(output_dir,paste0("2a.Lymphocytes_across_timepoints.pdf")),width = 1.2*3, height = 1.0*2.5)

##plot 2b
#statistical calculation (68% CI = mean ± 1*SE)
summary_df_Neutrophils <- Neutrophils %>%
  group_by(Day, Group,Type) %>%
  summarise(
    mean_val = mean(Value, na.rm = TRUE),      
    sd_val = sd(Value, na.rm = TRUE),
    n = sum(!is.na(Value)),
    se_val = sd_val / sqrt(n),
    ci_low = mean_val - se_val,   
    ci_high = mean_val + se_val
  )
#plot
Neutrophils_plot <- ggplot(summary_df_Neutrophils, aes(x = Day, y = mean_val, group = Group, 
                                                       color = Group, fill = Group)) +
  geom_line(size = 0.5) +
  geom_point(size = 1.2) +
  geom_ribbon(aes(ymin = ci_low, ymax = ci_high), alpha = 0.1, color = NA) +
    scale_color_manual(values = c("HPC" = HPC_base, "MNC" = MNC_base)) +
  scale_fill_manual(values = c("HPC" = HPC_base, "MNC" = MNC_base)) +
  labs(x = "Day relative to collection",
       y = "Neutrophils \n(% of CD15+ to CD45+ cells)") +
  theme_bw()+
  facet_grid(Group~Type)
#save plot
ggsave(paste0(output_dir,paste0("2b.Neutrophils_across_timepoints.pdf")),width = 1.2*3, height = 1.0*2.5)

##plot 2c
#statistical calculation (68% CI = mean ± 1*SE)
summary_df_Monocytes <- Monocytes %>%
  group_by(Day, Group,Type) %>%
  summarise(
    mean_val = mean(Value, na.rm = TRUE),      
    sd_val = sd(Value, na.rm = TRUE),
    n = sum(!is.na(Value)),
    se_val = sd_val / sqrt(n),
    ci_low = mean_val - se_val,   
    ci_high = mean_val + se_val
  )
#plot
Monocytes_plot <- ggplot(summary_df_Monocytes, aes(x = Day, y = mean_val, group = Group, 
                                                       color = Group, fill = Group)) +
  geom_line(size = 0.5) +
  geom_point(size = 1.2) +
  geom_ribbon(aes(ymin = ci_low, ymax = ci_high), alpha = 0.1, color = NA) +
    scale_color_manual(values = c("HPC" = HPC_base, "MNC" = MNC_base)) +
  scale_fill_manual(values = c("HPC" = HPC_base, "MNC" = MNC_base)) +
  labs(x = "Day relative to collection",
       y = "Monocytes \n(% CD14/16+ to CD45+ cells)") +
  ylim(10,50)+
  theme_bw()+
  facet_grid(Group~Type)
#save plot
ggsave(paste0(output_dir,paste0("2c.Monocytes_across_timepoints.pdf")),width = 1.2*3, height = 1.0*2.5)

```

# Figure.S1. CD34+(S1a), T,B,NK(S1b), and MLR,NLR (S1c)
```{r plot figure.S1a, S1b and S1c}
##plot S1a
#statistical calculation (68% CI = mean ± 1*SE)
summary_df_CD34 <- CD34 %>%
  group_by(Day, Group) %>%
  summarise(
    mean_val = mean(Value, na.rm = TRUE),      
    sd_val = sd(Value, na.rm = TRUE),
    n = sum(!is.na(Value)),
    se_val = sd_val / sqrt(n),
    ci_low = mean_val - se_val,   
    ci_high = mean_val + se_val
  )
#plot
CD34_plot <- ggplot(summary_df_CD34, aes(x = Day, y = mean_val, group = Group, color = Group, fill = Group)) +
  geom_line(size = 0.5) +
  geom_point(size = 1.2) +
  geom_ribbon(aes(ymin = ci_low, ymax = ci_high), alpha = 0.1, color = NA) +
    scale_color_manual(values = c("HPC" = HPC_base, "MNC" = MNC_base)) +
  scale_fill_manual(values = c("HPC" = HPC_base, "MNC" = MNC_base)) +
  labs(title = "CD34+", x = "Day relative to collection",
       y = "CD34+ (%)") +
  ylim(0.2,1.3)+
  theme_bw()
#save plot
ggsave(paste0(output_dir,paste0("S1a.CD34+_across_timepoints.pdf")),width = 1.2*3, height = 1.0*2.5)

##plot s1b
#statistical calculation (68% CI = mean ± 1*SE)
summary_df_TBNK <- TBNK %>%
  group_by(Day, Group,Type) %>%
  summarise(
    mean_val = mean(Value, na.rm = TRUE),      
    sd_val = sd(Value, na.rm = TRUE),
    n = sum(!is.na(Value)),
    se_val = sd_val / sqrt(n),
    ci_low = mean_val - se_val,   
    ci_high = mean_val + se_val
  )
#plot
TBNK_plot <- ggplot(summary_df_TBNK, aes(x = Day, y = mean_val, group = Group, 
                                                       color = Group, fill = Group)) +
  geom_line(size = 0.5) +
  geom_point(size = 1.2) +
  geom_ribbon(aes(ymin = ci_low, ymax = ci_high), alpha = 0.1, color = NA) +
    scale_color_manual(values = c("HPC" = HPC_base, "MNC" = MNC_base)) +
  scale_fill_manual(values = c("HPC" = HPC_base, "MNC" = MNC_base)) +
  labs(x = "Day relative to collection",
       y = "% to CD45+ cells") +
  theme_bw()+
  facet_grid(Group~Type)
#save plot
ggsave(paste0(output_dir,paste0("S1b.TBNK_across_timepoints.pdf")),width = 2.4*3, height = 1.0*2.5)

##plot s1c
#statistical calculation (68% CI = mean ± 1*SE)
summary_df_NLRMLR <- NLRMLR %>%
  group_by(Day, Group,Type) %>%
  summarise(
    mean_val = mean(Value, na.rm = TRUE),      
    sd_val = sd(Value, na.rm = TRUE),
    n = sum(!is.na(Value)),
    se_val = sd_val / sqrt(n),
    ci_low = mean_val - se_val,   
    ci_high = mean_val + se_val
  )
#plot
NLRMLR_plot <- ggplot(summary_df_NLRMLR, aes(x = Day, y = mean_val, group = Group, 
                                                       color = Group, fill = Group)) +
  geom_line(size = 0.5) +
  geom_point(size = 1.2) +
  geom_ribbon(aes(ymin = ci_low, ymax = ci_high), alpha = 0.1, color = NA) +
    scale_color_manual(values = c("HPC" = HPC_base, "MNC" = MNC_base)) +
  scale_fill_manual(values = c("HPC" = HPC_base, "MNC" = MNC_base)) +
  labs(title = " ", x = "Day relative to collection",
       y = "Ratio") +
  theme_bw()+
  facet_grid(Group ~ Type)
#save plot
ggsave(paste0(output_dir,paste0("S1c.NLRMLR_across_timepoints.pdf")),width = 2.4*2, height = 1.0*2.5)

```

# Figure.3a,3b,3c,and 3d
```{r plot figure 3a/3b/3c/3d}
#3a, pca for hpc samples
#plot
hpc_pca_plot <- ggplot(hpc_PCA, aes(x = -PC1, y = -PC2)) +
  geom_text_repel(aes(label = Day_Donor, color = Day), size = 3.5, max.overlaps = 20,segment.color = NA) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "grey70") +
  geom_vline(xintercept = 0, linetype = "dashed", color = "grey70") +
  labs(x = "PC1 (57%)", y = "PC2 (18.1%)") +
  ggtitle("HPC samples") +
  theme_classic() +
  theme(legend.position = "none")+
  scale_color_manual(values = HPC_day_color) +
  scale_x_continuous(labels = label_scientific()) +
  scale_y_continuous(labels = label_scientific()) 
#save
ggsave(paste0(output_dir,paste0("3a.PCA_HPC.pdf")),width = 3*2, height = 2.5*2)

#3b, dendrogram for hpc samples
#plot
hpc_ExpressionTPM <- as.data.frame(hpc_ExpressionTPM)  #tibble disabled to show the rownames.
rownames(hpc_ExpressionTPM) <- make.names(hpc_ExpressionTPM$Symbol,unique = TRUE)
hpc_ExpressionTPM <- hpc_ExpressionTPM[,-1]
expressionData_3 <- as.data.frame(t(hpc_ExpressionTPM))
hc <- hclust(dist(expressionData_3))
dendro_data <- dendro_data(hc, type = "rectangle")
sample_info_hpc <- data.frame(
  label = colnames(hpc_ExpressionTPM),  # match sample names
  Donor = c(rep("Donor1",5),rep("Donor2",5),rep("Donor3",5),
              rep("Donor4",5),rep("Donor5",5),rep("Donor6",5),rep("Donor7",5)), 
  Time = c(rep(c("Day0","Day1","Day2","Day3","Day4"),7)) # time points
  )
  labels <- dendro_data$labels
  labels <- merge(labels, sample_info_hpc, by = "label")
 hpc_dengrogram <- ggplot() +
  geom_segment(data = dendro_data$segments,
               aes(x = x, y = y, xend = xend, yend = yend)) +
  geom_point(data = labels,
             aes(x = x, y = y, color = Time),shape = 16, size = 3,stroke = 1) +
  geom_text(data = labels,
            aes(x = x, y = y - 1200, label = Donor),  # adjust `-2` to control vertical spacing
            size = 3, angle = 90,vjust = 0.25) +
  scale_color_manual(values = HPC_day_color) +  # or define your own Donor color palette
  # scale_shape_manual(values = c(0,1,2,3,4,8,13)) +  # adjust as needed
  theme_minimal() +
  labs(title = "HPC Dendrogram", x = NULL, y = "Distance") +
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank())
#save
ggsave(paste0(output_dir,paste0("3b.Dendrogram_HPC.pdf")),width = 5*2, height = 2*2)

#3c, pca for mnc samples
#plot
mnc_pca_plot <-  ggplot(mnc_PCA, aes(x = -PC1, y = -PC2)) +
  # geom_point(aes(shape = Day),size = 5, stroke = 1.2) +
  # scale_shape_manual(values = c(0,1,2,3,4)) +
  geom_text_repel(aes(label = Donor, color = Day), size = 3.5, max.overlaps = 20,segment.color = NA) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "grey70") +
  geom_vline(xintercept = 0, linetype = "dashed", color = "grey70") +
  labs(x = "PC1 (78.7%)", y = "PC2 (16.4%)") +
  ggtitle("MNC samples") +
  theme_classic() +
  theme(legend.position = "none")+
  scale_color_manual(values = MNC_day_color) +
  scale_x_continuous(labels = label_scientific()) +
  scale_y_continuous(labels = label_scientific()) 
#save
ggsave(paste0(output_dir,paste0("3c.PCA_MNC.pdf")),width = 3*2, height = 2.5*2)

#3d, dendrogram for mnc samples
#plot
rownames(mnc_ExpressionTPM) <- mnc_ExpressionTPM$Symbol
mnc_ExpressionTPM <- mnc_ExpressionTPM[,-1]
expressionData_3 <- as.data.frame(t(mnc_ExpressionTPM))
hc <- hclust(dist(expressionData_3))
dendro_data <- dendro_data(hc, type = "rectangle")
sample_info_mnc <- data.frame(
    label = colnames(mnc_ExpressionTPM),  # match sample names
    Donor = c(rep("Donor1",5),rep("Donor2",5),rep("Donor3",5),
              rep("Donor4",5),rep("Donor5",5),rep("Donor6",5)), 
    Time = c(rep(c("Day0","Day1","Day2","Day3","Day4"),6)) # time points
  )
  labels <- dendro_data$labels
  labels <- merge(labels, sample_info_mnc, by = "label")
 mnc_dengrogram <-  ggplot() +
  geom_segment(data = dendro_data$segments,
               aes(x = x, y = y, xend = xend, yend = yend)) +
  geom_point(data = labels,
             aes(x = x, y = y, color = Time),shape = 16, size = 3,stroke = 1) +
  geom_text(data = labels,
            aes(x = x, y = y - 9000, label = Donor),  # adjust `-2` to control vertical spacing
            size = 3, angle = 90,vjust = 0.25) +
  scale_color_manual(values = MNC_day_color) +  # or define your own Donor color palette
  theme_minimal() +
  labs(title = "MNC Dendrogram", x = NULL, y = "Distance") +
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank())
#save
ggsave(paste0(output_dir,paste0("3d.Dendrogram_MNC.pdf")),width = 5*2, height = 2*2)
```

# Figure.4a,4b
```{r plot figure 4a/4b}
#4a, heatmap for hpc samples
#pre-processing
rownames(sample_info_hpc) <- sample_info_hpc$label
hpc_ExpressionTPM[1:5,1:5]
expr_scaled_hpc <- t(scale(t(hpc_ExpressionTPM)))
expr_scaled_hpc[1:5,1:5]
expr_scaled_clean_hpc <- expr_scaled_hpc[complete.cases(expr_scaled_hpc) & rowSums(is.finite(expr_scaled_hpc)) == ncol(expr_scaled_hpc), ]
#plot
 heatmap_hpc <- Heatmap(
  expr_scaled_clean_hpc,
  name = "Z-score",
  col = heatmap_colors,
  cluster_rows = TRUE,
  cluster_columns = FALSE, # supervised: you can order by time
  column_split = factor(sample_info_hpc$Donor, 
                        levels = c("Donor1", "Donor2", "Donor3", 
                                   "Donor4", "Donor5","Donor6","Donor7")),
  column_title_gp = gpar(fontsize = 9),
  row_dend_gp = gpar(lwd = 0.1,col = "grey70"),
  show_column_names = FALSE,
  show_row_names = FALSE,
  use_raster = FALSE,
  top_annotation = HeatmapAnnotation(
    Time = sample_info_hpc$Time,
    col = list(Time = setNames(HPC_day_color, paste0("Day", 0:4))),
    annotation_name_gp = gpar(fontsize = 9),            # <- font size for "Time"
    simple_anno_size = unit(0.2,"cm")                  # <- annotation bar height
  )
)
#save
pdf(paste0(output_dir, "4a.heatmap_hpc.pdf"), width = 4*2, height = 2.5*2)
draw(heatmap_hpc)
dev.off()

#4b, heatmap for mnc samples
#pre-processing
rownames(sample_info_mnc) <- sample_info_mnc$label
expr_scaled_mnc <- t(scale(t(mnc_ExpressionTPM)))
expr_scaled_clean_mnc <- expr_scaled_mnc[complete.cases(expr_scaled_mnc) & rowSums(is.finite(expr_scaled_mnc)) == ncol(expr_scaled_mnc), ]
#plot
 heatmap_mnc <-   Heatmap(
  expr_scaled_clean_mnc,
  name = "Z-score",
  col = heatmap_colors,
  cluster_rows = TRUE,
  cluster_columns = FALSE, # supervised: you can order by time
  column_split = factor(sample_info_mnc$Donor, 
                        levels = c("Donor1", "Donor2", "Donor3", 
                                   "Donor4", "Donor5","Donor6")),
  column_title_gp = gpar(fontsize = 9),
  row_dend_gp = gpar(lwd = 0.1,col = "grey70"),
  show_column_names = FALSE,
  show_row_names = FALSE,
  use_raster = FALSE,
  top_annotation = HeatmapAnnotation(
    Time = sample_info_mnc$Time,
    col = list(Time = setNames(MNC_day_color, paste0("Day", 0:4))),
    annotation_name_gp = gpar(fontsize = 9),            # <- font size for "Time"
    simple_anno_size = unit(0.2,"cm")                  # <- annotation bar height
  )
)
#save
pdf(paste0(output_dir, "4a.heatmap_mnc.pdf"), width = 4*2, height = 2.5*2)
draw(heatmap_mnc)
dev.off()
```

# Figure.4c, 4d
```{r plot figure 4c,4d}
# 4c, most significantly changed genes in HPC samples between day0 and day1.
#pre-processing
  day0 <- grep("Day0", colnames(expr_scaled_hpc))
  day1 <- grep("Day1", colnames(expr_scaled_hpc))
  gene_diff <- rowMeans(expr_scaled_hpc[, day1]) - rowMeans(expr_scaled_hpc[, day0])
  gene_diff[1:10]
  top_genes <- names(sort(abs(gene_diff), decreasing = TRUE))[1:100]  # You can change 50
  top_genes
  heatmap_matrix <- expr_scaled_hpc[top_genes, ]
  heatmap_matrix_day0day1 <- heatmap_matrix[, grep("Day0|Day1", colnames(heatmap_matrix))]
  sample_info_day0day1 <-  data.frame(
    label = colnames(heatmap_matrix_day0day1),  # match sample names
    Donor = c(rep("Donor1",2),rep("Donor2",2),rep("Donor3",2),
              rep("Donor4",2),rep("Donor5",2),rep("Donor6",2),rep("Donor7",2)), 
    Time = c(rep(c("Day0","Day1"),7)) # time points
  )
  
#plot
 heatmap_hpc_day0vsday1 <- Heatmap(
  heatmap_matrix_day0day1,
  name = "Z-score",
  col = heatmap_colors,
  cluster_rows = TRUE,
  cluster_columns = FALSE, # supervised: you can order by time
  column_split = factor(sample_info_day0day1$Time, levels = c("Day0", "Day1")),
  column_title_gp = gpar(fontsize = 9),
  row_dend_gp = gpar(lwd = 0.1,col = "grey70"),
  show_column_names = FALSE,
  show_row_names = TRUE,
  use_raster = FALSE,
  row_names_gp = gpar(fontsize = 3.5), 
  top_annotation = HeatmapAnnotation(
    Time = sample_info_day0day1$Time,
    col = list(Time = setNames(HPC_colors_day0day1, paste0("Day", 0:1))),
    annotation_name_gp = gpar(fontsize = 9),            # <- font size for "Time"
    simple_anno_size = unit(0.3,"cm")                  # <- annotation bar height
  )
)
#save
pdf(paste0(output_dir, "4c.heatmap_hpc_day0vsday1.pdf"), width = 2*2, height = 2.5*2)
draw(heatmap_hpc_day0vsday1)
dev.off()

# 4d, enriched pathways for top100 significantly changed genes
#pre-processing
gene_df <- bitr(top_genes, fromType = "SYMBOL",
                  toType = "ENTREZID",
                  OrgDb = org.Hs.eg.db)
ego <- enrichGO(gene = gene_df$ENTREZID,
                  OrgDb = org.Hs.eg.db,
                  keyType = "ENTREZID",
                  ont = "BP",      # or "MF", "CC"
                  pAdjustMethod = "BH",
                  pvalueCutoff = 0.05,
                  qvalueCutoff = 0.2)
reactome <- enrichPathway(gene = gene_df$ENTREZID,
                            organism = "human",
                            pvalueCutoff = 2)
reactome_results <- reactome@result
top_pathways <- reactome_results[order(reactome_results$pvalue, decreasing = FALSE), ][1:4, ]
top_pathways
#plot
top100Pathway <- ggplot(reactome_results, aes(x = FoldEnrichment, y = -log10(pvalue), size = Count, color = p.adjust)) +
  geom_point(alpha = 0.7) +
  scale_color_gradientn(colors = heatmap_colors) +  # Color by adjusted p-value
  geom_text(data = top_pathways, aes(label = c("TGF-beta receptor signaling",
                                               "Cellular surface GPI-anchored proteins",
                                               "c",
                                               "Transport of vitamins, nucleosides, and related molecules")), 
            check_overlap = TRUE,  # Avoid overlapping labels
            size = 2.5,              # Adjust label size
            nudge_y = 0.1,         # Nudge labels slightly to avoid overlap
            nudge_x = 2.6,
            color = pathway_color) +     # Label color
  theme_minimal() +
  labs(x = "Fold Enrichment",
       y = "-Log10(p-value)",
       color = "Adjusted p-value",
       size = "Gene Count") +
  theme(legend.position = "right") +
  theme(axis.text.x = element_text(size = 6.5,hjust = 1),
        axis.text.y = element_text(size = 6.5),
        axis.title.x = element_text(size = 8),
        axis.title.y = element_text(size = 8),
        title = element_text(size = 2),
        legend.title = element_text(size = 8)
  ) 
#save
ggsave(paste0(output_dir, paste0("4d.top100_genes_pathway.pdf")), width = 2.5*2, height = 1.8*2)
```

